on:
  push:
    branches:
      - dev
name: 🚀 Deploy Dev Willow on push
jobs:
  web-deploy:
    name: 🎉 Deploy Dev Willow
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.dev.mountainspringsrecovery.com
          username: ${{ secrets.dev_ftp_username }}
          password: ${{ secrets.dev_ftp_password }}
          server-dir: /dev.willowspringsrecovery.com/wp-content/themes/sbh_center_3.2/
